firstproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("polls.urls"))
]

polls/urls.py
from django.urls import path
from .views import index, contact, about, detail


app_name = 'polls'

urlpatterns = [
    path("", index, name='home'),
    path("contact", contact, name='contact_us'),
    path("about", about, name='about'),
    path('detail/<int:question_id>/', detail, name='detail')


]

polls/models.py
from django.db import models


# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200, unique=True)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Student(models.Model):
    Name = models.CharField(max_length=200,)
    Gender = models.CharField(max_length=200)
    State = models.CharField(max_length=200)
    Age_field = models.IntegerField(default=0)


    def __str__(self):
        return self.Name

polls/forms.py
from django import forms

class FormName(forms.Form):
    name = forms.CharField(max_length=200)
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)

polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice, Student

# Create your views here.


def index(request):
    questions = Question.objects.all()
    # choices = Choice.objects.all()
    # data = Student.objects.all()

    context = {
        'questions': questions,
        # 'choices': choices,
        # 'data': data,


    }

    return render(request, "index.html", context)


def contact(request):
    return render(request, "contact.html")


def about(request):
    context = {
        'address': "Area E, Nyanya road.Abuja",
        'contact': "08146124879"
    }

    return render(request, "about.html", context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question

    }
    return render(request, "detail.html", context)

templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About us</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<h1>About us</h1>
<p>Address:{{address}}</p>
<p>contact:{{contact}}</p>

<a href="{% url 'polls:home' %}">home page</a>
<a href="{% url 'polls:contact_us' %}">talk to us</a>
<img src="{% static 'images/house2.jpg' %}" >

</body>
</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>contact</title>
</head>
<body>
<h1>contact us here</h1>



{% if choices %}
    {% for choice in choices %}
    <h2>{{ choice.choice_text.upper }} | <small>{{ choice.pub_date.date }}</small></h2>
    {% endfor %}
{% else %}
<p>no polls available.</p>
{% endif %}


<h1>Student Data</h1>
<div class="list">
    {% if data%}
     <table border="1" cellpadding="6px"  >
        <thead>
            <th>Name</th>
            <th>Gender</th>
            <th>State</th>
            <th>Age</th>
        </thead>

         {% for data in data %}
        <tr>
            <td>{{data.Name}}</td>
            <td>{{data.Gender}}</td>
            <td>{{data.State}}</td>
            <td>{{data.Age_field}}</td>
        </tr>
        {% endfor %}
    {% else %}
    <p>cannot display table</p>
    {% endif %}
    </table>
</div>
<a href="{% url 'polls:about' %} ">about page</a>
<img src="{% static 'images/house.jpg' %}" alt="">
<img src="{% static 'images/library.jpg' %}" >
</body>
</html>

templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>
<h1>{{question.upper}}</h1>
<ol type="A">
{% for choice in question.choice_set.all %}
<li>{{choice.choice_text}}</li>
{% endfor %}
</ol>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home page</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<center>
<h1>welcome to the polls app</h1>

{% if questions %}
    {% for question in questions %}
    <h3><a href="{% url 'polls:detail' question.id %}">{{ question.question_text.upper }}</a> | <small>{{ question.pub_date.date }}</small></h3>
    {% endfor %}
{% else %}
<p>no polls available.</p>
{% endif %}
</center>




</body>
</html>